import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dbConnect from '../lib/dbConnect'
import Movie from '../models/Movie'
import Link from 'next/link'

export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>Movies</h1>
        {
          movies.map(({ _id, title, plot }) => (
            <Link href={_id} key={_id}>
              <a className="card mb-2">
                <div className="card-body">
                  <div className="h5 text-uppercase">{title}</div>
                  <div className="text-muted">{plot}</div>
                </div>
              </a>
            </Link>
          ))
        }
        <Link href="/new">
          <a className='btn btn-primary w-100'>Add new movie</a>
        </Link>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  try {
    await dbConnect()
    const res = await Movie.find({})
    const movies = res.map(doc => {
      const movie = doc.toObject()
      movie._id = movie._id.toString()
      return movie
    })
    return {
      props: {
        movies
      }
    }
  } catch (err) {
    console.log(err)
  }
}